<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MENU_pc-link</name>
   <tag></tag>
   <elementGuidId>3bf14dac-931c-40e2-8958-71d631e2e5e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.pc-item.pc-hasmenu > a.pc-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[normalize-space() = 'Stock']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Stock&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1817bc12-8d96-448b-b96c-7c452ff561a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#!</value>
      <webElementGuid>92e6757b-74ac-47c3-abdc-cb8b7cecbba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pc-link</value>
      <webElementGuid>6a32e1b0-6a23-40ff-a9c8-b56cef40df6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Stock</value>
      <webElementGuid>70eebc52-58d2-41ee-beb1-e7d85a2e1586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;pc-sidebar pc-trigger&quot;]/div[@class=&quot;navbar-wrapper&quot;]/div[@class=&quot;navbar-content pc-trigger active&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/ul[@class=&quot;pc-navbar&quot;]/li[@class=&quot;pc-item pc-hasmenu&quot;]/a[@class=&quot;pc-link&quot;]</value>
      <webElementGuid>d904ca02-a032-471b-bdc4-14e17a9e68b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENU'])[1]/following::a[1]</value>
      <webElementGuid>c3ef1061-db86-480f-90ba-29145fec8f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>a2ecce39-396e-47b6-81be-24cee51d50c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#!')]</value>
      <webElementGuid>31fe8618-5c22-454b-ae64-1d33366eba37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>f4a82b19-a1eb-4c48-95ca-accaa8e246ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[normalize-space()='Stock']</value>
      <webElementGuid>50fab7f7-3658-42af-ab3b-134b86036b02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
