<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Catatan_dom-jqry_paginate</name>
   <tag></tag>
   <elementGuidId>d65ad72a-d714-4781-9a0b-089a184e71a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dom-jqry_paginate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dom-jqry_paginate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dom-jqry_paginate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2426f245-33e1-43e6-87b2-9d85e3dcd332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_paginate paging_simple_numbers</value>
      <webElementGuid>ce7f92ea-5d8a-4c4b-8752-98b60f6ea01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dom-jqry_paginate</value>
      <webElementGuid>0fd83def-da39-431d-98d0-b33c757bd2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous12Next</value>
      <webElementGuid>8265d16d-5ee8-4114-a49c-2bf2a563030a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dom-jqry_paginate&quot;)</value>
      <webElementGuid>e8a7139c-77b7-461d-b2c0-473709b81eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dom-jqry_paginate']</value>
      <webElementGuid>d8ed3438-685d-4eba-801c-cd709bc4252b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dom-jqry_wrapper']/div[2]/div</value>
      <webElementGuid>e10baac3-fdbb-4bca-8203-ed0ec80cb998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[1]/following::div[2]</value>
      <webElementGuid>730dac8c-2b04-4a13-8b84-cf1c75277290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[2]</value>
      <webElementGuid>d570a1e7-fe61-46fc-9fd5-3118da6a2158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>bfc3276d-2d17-45a6-82c3-b9eac75931d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dom-jqry_paginate' and (text() = 'Previous12Next' or . = 'Previous12Next')]</value>
      <webElementGuid>4eb5a485-237a-4a84-935f-f55f6c419d6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
