<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_form-control</name>
   <tag></tag>
   <elementGuidId>525fdaac-4c00-4b02-af6f-60a850e9f219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-group.mb-3 > input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Palembang1@']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[type=&quot;password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62774f33-14ae-46a1-8771-02e61de71fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>14ec495f-1658-4468-8d97-0b1844159aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd716e95-ba8b-476b-b353-d2d44c8e496d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Palembang1@</value>
      <webElementGuid>4898cab6-f8fb-434c-b7ba-12cc24a55581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;position-relative overflow-hidden radial-gradient min-vh-100 w-100&quot;]/div[@class=&quot;position-relative z-index-5 bg-white&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-5 col-xxl-4&quot;]/div[@class=&quot;authentication-login min-vh-100 bg-body row justify-content-center align-items-center p-4&quot;]/div[@class=&quot;col-sm-8 col-md-6 col-xl-9&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;input-group mb-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>bef3c5e7-7eb8-40b8-a379-9a20386dcbd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Palembang1@']</value>
      <webElementGuid>ad2d445a-8aaa-4205-9980-c1a78b326bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>ef4447eb-7c88-476b-a494-a54509cd0235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c2b0005e-04be-441d-970b-234ad08decc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>972c5df6-4732-4386-8342-3f4f4a6e578f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
