<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_form-control</name>
   <tag></tag>
   <elementGuidId>a99e88ab-d3df-4116-a3c7-95a6a6484f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='12345']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-group.mb-3 > input.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[type=&quot;password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de249650-bd0b-4a54-b7e0-a159ca66baf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>079e63cb-3709-45f8-9d78-f557dc2959af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cc986325-02c8-47e2-a7b2-27ecf0bb2a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>bdaa4fe6-da73-43da-9e44-7155f1e7cc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;position-relative overflow-hidden radial-gradient min-vh-100 w-100&quot;]/div[@class=&quot;position-relative z-index-5 bg-white&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-5 col-xxl-4&quot;]/div[@class=&quot;authentication-login min-vh-100 bg-body row justify-content-center align-items-center p-4&quot;]/div[@class=&quot;col-sm-8 col-md-6 col-xl-9&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;input-group mb-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>eb4bd603-aa2f-407c-a383-77d3fe2a74af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='12345']</value>
      <webElementGuid>96ed96bb-1550-4adf-b43f-1ee9d913f7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>7d8dc52b-95d8-4873-9343-36eaf7e14c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>984366c7-36b2-432c-a588-a3d240796dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>6af34db1-62fe-49b0-b560-096ae468bc2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
