<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_form-control_1</name>
   <tag></tag>
   <elementGuidId>9012bbd0-a20f-4b3b-8c40-46b210df31f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='2401320001']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>717f54db-dd95-418a-8e81-fb195c2ea27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>659b5fc5-8d05-4b13-be1b-c7002610560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b1470ac1-6247-49dc-bea7-d283473011fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2401320001</value>
      <webElementGuid>c40432f2-0a60-4a05-95b7-98809f1d1c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;position-relative overflow-hidden radial-gradient min-vh-100 w-100&quot;]/div[@class=&quot;position-relative z-index-5 bg-white&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-5 col-xxl-4&quot;]/div[@class=&quot;authentication-login min-vh-100 bg-body row justify-content-center align-items-center p-4&quot;]/div[@class=&quot;col-sm-8 col-md-6 col-xl-9&quot;]/div[@class=&quot;mb-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>00d46ff2-9fc9-4b97-81f9-7cf55fc9b786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='2401320001']</value>
      <webElementGuid>1707c5ed-5a09-4262-97bd-52055d1f0e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>359c45e3-d646-48aa-9874-0d8ad2e83ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a589a905-47c8-45a1-8557-018a672ffcd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>e2f9a230-1729-4c97-b0fd-1421840e5aaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
