<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_form-control_7</name>
   <tag></tag>
   <elementGuidId>519d9907-9e92-4ac3-ab3d-2c7c6e7d513e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Palemban']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-group.mb-3 > input.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[type=&quot;password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e80582d-ea8f-4a1a-93eb-519e30069d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bf6fc088-6a6a-4145-97f5-2f46109017fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a4cf3b84-f663-45e1-8eb0-aeff68935976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Palemban</value>
      <webElementGuid>e19ed4b7-f821-4017-9481-1e72513342fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;position-relative overflow-hidden radial-gradient min-vh-100 w-100&quot;]/div[@class=&quot;position-relative z-index-5 bg-white&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-5 col-xxl-4&quot;]/div[@class=&quot;authentication-login min-vh-100 bg-body row justify-content-center align-items-center p-4&quot;]/div[@class=&quot;col-sm-8 col-md-6 col-xl-9&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;input-group mb-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a8ac11fb-dc7f-4db5-8830-152bf9d8793f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Palemban']</value>
      <webElementGuid>5354adf1-65b4-424a-91f2-e055318c77a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>2f4edb16-a8c0-41f6-8501-5c3621ed9900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>de919f4c-7bbc-4f4e-bbdb-71582c518717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>7b9aa0a7-3507-495f-9fba-d3ae7dd91d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
